name             'windows_uac'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache-2.0'
description      'Provides a resource for enabling and disabling UAC on Windows'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.0'
supports         'windows'
source_url       'https://github.com/chef-cookbooks/windows_uac'
issues_url       'https://github.com/chef-cookbooks/windows_uac/issues'
chef_version     '>= 13.9'
